= Changelog

:sectnums!:

== link:++https://github.com/saltstack-formulas/sysstat-formula/compare/v0.4.0...v0.4.1++[0.4.1^] (2020-12-16)

=== Continuous Integration

* *gemfile.lock:* add to repo with updated `Gemfile` [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/0bac4d9f248d4ccdf0843528dea594e98ca45dfd[0bac4d9^])
* *gitlab-ci:* use GitLab CI as Travis CI replacement
(https://github.com/saltstack-formulas/sysstat-formula/commit/371749edbe66fe2ed3193467d63a99217f01852b[371749e^])
* *kitchen:* use `saltimages` Docker Hub where available [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/fca90fff36c58e98d1586141275b5e0cae2e7707[fca90ff^])
* *kitchen+travis:* remove `master-py2-arch-base-latest` [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/e5c83d2768554905c33ecd4ac2f17227098e1513[e5c83d2^])
* *pre-commit:* add to formula [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/7196f19eed3a9833e85ce554fe3880c5b69a7869[7196f19^])
* *pre-commit:* enable/disable `rstcheck` as relevant [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/06d84db06d3745106b889ec3a296f831ece02a9c[06d84db^])
* *pre-commit:* finalise `rstcheck` configuration [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/bf59577f3a5c49841e27856a91ec355262a4f52c[bf59577^])
* *travis:* add notifications => zulip [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/e7ee82da861a0787f10511a2b1034c2a43525e8a[e7ee82d^])
* *workflows/commitlint:* add to repo [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/38e980f4e7e3c121390d129d0b7c426b2a4433a8[38e980f^])

=== Styles

* *libtofs.jinja:* use Black-inspired Jinja formatting [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/06139cef593009d10724401054b860cda49c0d25[06139ce^])

== link:++https://github.com/saltstack-formulas/sysstat-formula/compare/v0.3.0...v0.4.0++[0.4.0^] (2020-03-28)

=== Bug Fixes

* *libtofs:* “files_switch” mess up the variable exported by “map.jinja”
 [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/47470ba27415b0bee3e0244d236bb86b11593c7f[47470ba^])
* *release.config.js:* use full commit hash in commit link [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/d60feaf42abd27c4bd3d178cc8f6c091d759af7a[d60feaf^])

=== Continuous Integration

* *gemfile:* restrict `train` gem version until upstream fix [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/15c184760f62c8094e1c2c1057f0f5817fb60571[15c1847^])
* *kitchen:* avoid using bootstrap for `master` instances [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/98b1708327b9c6155512527d27c5119fe9217f2d[98b1708^])
* *kitchen:* change `log_level` to `debug` instead of `info`
(https://github.com/saltstack-formulas/sysstat-formula/commit/f29dadb2462299f543af5b1fa4bd5b7b51dcd2f6[f29dadb^])
* *kitchen:* install required packages to bootstrapped `opensuse` [skip
ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/c2a22b54b58f76703209c5a5da37a779ac459cba[c2a22b5^])
* *kitchen:* use `debian-10-master-py3` instead of `develop` [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/9a0551cde11224a829b912d43bc5063e2671323a[9a0551c^])
* *kitchen:* use `develop` image until `master` is ready (`amazonlinux`)
 [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/9c99c79426aac0e1085a4e32d59efcf4c9d6c09a[9c99c79^])
* *kitchen:* use bootstrapped `opensuse` images until `2019.2.2` [skip
ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/72b7884ddba7a3d423af5ced968c5b2d2f87d231[72b7884^])
* *kitchen+travis:* replace EOL pre-salted images
(https://github.com/saltstack-formulas/sysstat-formula/commit/b9e16d5a3760f4651919b2a2d132a9574d162925[b9e16d5^])
* *kitchen+travis:* upgrade matrix after `2019.2.2` release [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/cfca07f9abcf784dd335e703e90ecfbf95488e37[cfca07f^])
* *platform:* add `arch-base-latest`
(https://github.com/saltstack-formulas/sysstat-formula/commit/c5db9a54b6c3958eb4ced5c3a91ea982612b4bb1[c5db9a5^])
* *travis:* apply changes from build config validation [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/e9b9c351d496acf7a1c328e42d4bb58c5eb5c278[e9b9c35^])
* *travis:* opt-in to `dpl v2` to complete build config validation [skip
ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/d49d6c51e340f5d9b5fe8e6517cee507f77ec937[d49d6c5^])
* *travis:* quote pathspecs used with `git ls-files` [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/c211ac523a7df476411a584f1a93d42388d3d424[c211ac5^])
* *travis:* run `shellcheck` during lint job [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/056d015f18e1cf21ef790af3e7e924667522c273[056d015^])
* *travis:* update `salt-lint` config for `v0.0.10` [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/64b821e19725db93f3c0b5b2aea722c352621ab7[64b821e^])
* *travis:* use `major.minor` for `semantic-release` version [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/ca4508ae0180e906f7b668b0031302750e580dd9[ca4508a^])
* *travis:* use build config validation (beta) [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/91489dd175bf0138ffc0f30d99a1f83497d808d8[91489dd^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/sysstat-formula/commit/2e40417837a791a61f39266b9ce858340bd6d62d[2e40417^])
* merge travis matrix, add `salt-lint` & `rubocop` to `lint` job
(https://github.com/saltstack-formulas/sysstat-formula/commit/29af05ef16824245dd989d6f81bf1d673f5f7f4a[29af05e^])
* *yamllint:* add rule `empty-values` & use new `yaml-files` setting
(https://github.com/saltstack-formulas/sysstat-formula/commit/2cea0b2894a7bc941cb11e46a896f3258a193c38[2cea0b2^])
* use `dist: bionic` & apply `opensuse-leap-15` SCP error workaround
(https://github.com/saltstack-formulas/sysstat-formula/commit/142ff661eb07b4911e65e46240076c3b48ba6953[142ff66^])

=== Documentation

* *contributing:* remove to use org-level file instead [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/4cf5a60f5946056a6e5c4db19b7f1fd1724936db[4cf5a60^])
* *readme:* update link to `CONTRIBUTING` [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/b5d30cf8e99012c182c09c8ca5988dc32247534e[b5d30cf^])

=== Features

* *os:* graceful fail for unsupported os
(https://github.com/saltstack-formulas/sysstat-formula/commit/be66570a0b0baa8b24b2fa46127e63ae28aa39e9[be66570^])

=== Performance Improvements

* *travis:* improve `salt-lint` invocation [skip ci]
(https://github.com/saltstack-formulas/sysstat-formula/commit/cf877cf4c79358b5f0265f5f19b9c2be41e39e29[cf877cf^])

== link:++https://github.com/saltstack-formulas/sysstat-formula/compare/v0.2.0...v0.3.0++[0.3.0^] (2019-08-17)

=== Features

* *yamllint:* include for this repo and apply rules throughout
(https://github.com/saltstack-formulas/sysstat-formula/commit/a8cc767[a8cc767^])

== link:++https://github.com/saltstack-formulas/sysstat-formula/compare/v0.1.0...v0.2.0++[0.2.0^] (2019-07-19)

=== Bug Fixes

* *example:* fix pillar example
(https://github.com/saltstack-formulas/sysstat-formula/commit/d4e6442[d4e6442^])
* *macro:* remove unused 'concat_args' macro
(https://github.com/saltstack-formulas/sysstat-formula/commit/ee6f30f[ee6f30f^])
* *suse:* correct the service name on suse
(https://github.com/saltstack-formulas/sysstat-formula/commit/d69bd4e[d69bd4e^])

=== Code Refactoring

* *formula:* align with template-formula v3.0.0
(https://github.com/saltstack-formulas/sysstat-formula/commit/873ae0f[873ae0f^])

=== Features

* *formula:* align with template-formula v3.0.0
(https://github.com/saltstack-formulas/sysstat-formula/commit/12a9c76[12a9c76^])
* *formula:* apply pr review comments
(https://github.com/saltstack-formulas/sysstat-formula/commit/ad30f21[ad30f21^])
* *formula:* apply pr review comments
(https://github.com/saltstack-formulas/sysstat-formula/commit/1e3cdc9[1e3cdc9^])

=== Tests

* *inspec:* fix unit test
(https://github.com/saltstack-formulas/sysstat-formula/commit/84e697a[84e697a^])
